import { render, screen } from "@testing-library/react";
import "@testing-library/jest-dom";
import Home from "../pages/index";

describe("Home page", () => {
  it("muestra el texto de inicio", () => {
    render(<Home />);
    expect(screen.getByText(/Get started by editing/i)).toBeInTheDocument();
  });

  it("muestra todos los enlaces principales", () => {
    render(<Home />);
    expect(screen.getByRole("link", { name: /Docs/i })).toBeInTheDocument();
    expect(screen.getByRole("link", { name: /Learn/i })).toBeInTheDocument();
    expect(
      screen.getByRole("link", { name: /Templates/i })
    ).toBeInTheDocument();
    expect(screen.getByRole("link", { name: /Deploy/i })).toBeInTheDocument();
  });

  it("muestra los títulos de las tarjetas", () => {
    render(<Home />);
    expect(screen.getByText(/Docs/i)).toBeInTheDocument();
    expect(screen.getByText(/Learn/i)).toBeInTheDocument();
    expect(screen.getByText(/Templates/i)).toBeInTheDocument();
    expect(screen.getByText(/Deploy/i)).toBeInTheDocument();
  });

  it("muestra las imágenes principales", () => {
    render(<Home />);
    expect(screen.getByAltText("Vercel Logo")).toBeInTheDocument();
    expect(screen.getByAltText("Next.js Logo")).toBeInTheDocument();
  });

  it("muestra el título y los metadatos en el Head", () => {
    render(<Home />);
    // El título no se puede comprobar directamente con screen, pero sí el meta description
    const meta = document.querySelector('meta[name="description"]');
    expect(meta).toHaveAttribute("content", "Generated by create next app");
    expect(document.title).toBe("Create Next App");
  });
});
