apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nextjs-app
  labels:
    app: my-nextjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nextjs-app
  template:
    metadata:
      labels:
        app: my-nextjs-app
    spec:
      # imagePullSecrets:
      #   - name: my-registry-secret # Descomenta si usas imágenes privadas
      containers:
        - name: app
          image: docker.io/gioanrobles/gioan-test-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: my-nextjs-app
spec:
  selector:
    app: my-nextjs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
